#!/bin/sh -e
#
# Install perfSONAR (Placeholder)
#

cat <<EOF

Hello there!

You have invoked a discontinued beta version of the perfSONAR
installation script.

Please use the production version, which is invoked the same way as
this one but lives at a different URL, e.g.:

curl -s https://raw.githubusercontent.com/perfsonar/project/master/install-perfsonar \\
  | sh -s - --auto-updates --tunings testpoint

EOF

exit 1
